/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumnosproject;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author angela
 */
public class Alumnos extends javax.swing.JFrame {
    /**
     * Creates new form Alumnos
     */
    Lista alumnos=new Lista();
    
    public Alumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operacionesButtonGroup = new javax.swing.ButtonGroup();
        paginasPanel = new javax.swing.JPanel();
        operacionesLabel = new javax.swing.JLabel();
        agregarRadioButton = new javax.swing.JRadioButton();
        buscarRadioButton = new javax.swing.JRadioButton();
        eliminarRadioButton = new javax.swing.JRadioButton();
        modificarRadioButton = new javax.swing.JRadioButton();
        botonesPanel = new javax.swing.JPanel();
        mostrarButton = new javax.swing.JButton();
        liberarListaButton = new javax.swing.JButton();
        contenidoPanel = new javax.swing.JPanel();
        agregarPanel = new javax.swing.JPanel();
        posicionLabel_Agregar = new javax.swing.JLabel();
        agregarInicioButton = new javax.swing.JButton();
        posicionTextField_Agregar = new javax.swing.JTextField();
        insertarButton = new javax.swing.JButton();
        agregarFinalButton = new javax.swing.JButton();
        nombreTextField_Agregar = new javax.swing.JTextField();
        nombreLabel_Agregar = new javax.swing.JLabel();
        codigoTextField_Agregar = new javax.swing.JTextField();
        codigoLabel_Agregar = new javax.swing.JLabel();
        modificarPanel = new javax.swing.JPanel();
        codigoLabel_Modificar = new javax.swing.JLabel();
        codigoTextField_Modificar = new javax.swing.JTextField();
        nuevoNombLabel_Modificar = new javax.swing.JLabel();
        nuevoNombTextField_Modificar = new javax.swing.JTextField();
        modificarButton = new javax.swing.JButton();
        eliminarPanel = new javax.swing.JPanel();
        codigoLabel_Eliminar = new javax.swing.JLabel();
        codigoTextField_Eliminar = new javax.swing.JTextField();
        posicionLabel_Eliminar = new javax.swing.JLabel();
        posicionTextField_Eliminar = new javax.swing.JTextField();
        eliminarButton = new javax.swing.JButton();
        buscarPanel = new javax.swing.JPanel();
        codigoLabel_Buscar = new javax.swing.JLabel();
        codigoTextField_Buscar = new javax.swing.JTextField();
        nombreLabel_Buscar = new javax.swing.JLabel();
        nombreTextField_Buscar = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        operacionesLabel.setText("Operaciones con alumnos");

        operacionesButtonGroup.add(agregarRadioButton);
        agregarRadioButton.setSelected(true);
        agregarRadioButton.setText("Agregar ");
        agregarRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarRadioButtonActionPerformed(evt);
            }
        });

        operacionesButtonGroup.add(buscarRadioButton);
        buscarRadioButton.setText("Buscar");
        buscarRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarRadioButtonActionPerformed(evt);
            }
        });

        operacionesButtonGroup.add(eliminarRadioButton);
        eliminarRadioButton.setText("Eliminar");
        eliminarRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarRadioButtonActionPerformed(evt);
            }
        });

        operacionesButtonGroup.add(modificarRadioButton);
        modificarRadioButton.setText("Modificar");
        modificarRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paginasPanelLayout = new javax.swing.GroupLayout(paginasPanel);
        paginasPanel.setLayout(paginasPanelLayout);
        paginasPanelLayout.setHorizontalGroup(
            paginasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginasPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(paginasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operacionesLabel)
                    .addGroup(paginasPanelLayout.createSequentialGroup()
                        .addComponent(agregarRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(buscarRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(modificarRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        paginasPanelLayout.setVerticalGroup(
            paginasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginasPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(operacionesLabel)
                .addGap(6, 6, 6)
                .addGroup(paginasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarRadioButton)
                    .addComponent(buscarRadioButton)
                    .addComponent(modificarRadioButton)
                    .addComponent(eliminarRadioButton))
                .addGap(35, 35, 35))
        );

        getContentPane().add(paginasPanel, java.awt.BorderLayout.NORTH);

        mostrarButton.setText("Mostrar");
        mostrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarButtonActionPerformed(evt);
            }
        });

        liberarListaButton.setText("Liberar lista");
        liberarListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberarListaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botonesPanelLayout = new javax.swing.GroupLayout(botonesPanel);
        botonesPanel.setLayout(botonesPanelLayout);
        botonesPanelLayout.setHorizontalGroup(
            botonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonesPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(mostrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(liberarListaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        botonesPanelLayout.setVerticalGroup(
            botonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(botonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarButton)
                    .addComponent(liberarListaButton))
                .addGap(30, 30, 30))
        );

        getContentPane().add(botonesPanel, java.awt.BorderLayout.SOUTH);
        botonesPanel.getAccessibleContext().setAccessibleParent(this);

        contenidoPanel.setLayout(new java.awt.CardLayout());

        posicionLabel_Agregar.setText("Posición");

        agregarInicioButton.setText("Agregar al inicio");
        agregarInicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarInicioButtonActionPerformed(evt);
            }
        });

        insertarButton.setText("Insertar");
        insertarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarButtonActionPerformed(evt);
            }
        });

        agregarFinalButton.setText("Agregar al final");
        agregarFinalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFinalButtonActionPerformed(evt);
            }
        });

        nombreLabel_Agregar.setText("Nombre");

        codigoLabel_Agregar.setText("Código");

        javax.swing.GroupLayout agregarPanelLayout = new javax.swing.GroupLayout(agregarPanel);
        agregarPanel.setLayout(agregarPanelLayout);
        agregarPanelLayout.setHorizontalGroup(
            agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarPanelLayout.createSequentialGroup()
                        .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nombreLabel_Agregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codigoLabel_Agregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoTextField_Agregar)
                            .addComponent(nombreTextField_Agregar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(agregarPanelLayout.createSequentialGroup()
                            .addComponent(posicionLabel_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(posicionTextField_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(insertarButton))
                        .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(agregarFinalButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregarInicioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        agregarPanelLayout.setVerticalGroup(
            agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel_Agregar)
                    .addComponent(codigoTextField_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel_Agregar)
                    .addComponent(nombreTextField_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicionLabel_Agregar)
                    .addComponent(posicionTextField_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertarButton))
                .addGap(22, 22, 22)
                .addComponent(agregarInicioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarFinalButton)
                .addGap(100, 100, 100))
        );

        contenidoPanel.add(agregarPanel, "Agregar");

        codigoLabel_Modificar.setText("Código");

        nuevoNombLabel_Modificar.setText("Nuevo nombre");

        modificarButton.setText("Modificar");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificarPanelLayout = new javax.swing.GroupLayout(modificarPanel);
        modificarPanel.setLayout(modificarPanelLayout);
        modificarPanelLayout.setHorizontalGroup(
            modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarPanelLayout.createSequentialGroup()
                        .addComponent(nuevoNombLabel_Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(nuevoNombTextField_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarPanelLayout.createSequentialGroup()
                        .addComponent(modificarButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(modificarPanelLayout.createSequentialGroup()
                        .addComponent(codigoLabel_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(codigoTextField_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        modificarPanelLayout.setVerticalGroup(
            modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel_Modificar)
                    .addComponent(codigoTextField_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoNombLabel_Modificar)
                    .addComponent(nuevoNombTextField_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(modificarButton)
                .addGap(170, 170, 170))
        );

        contenidoPanel.add(modificarPanel, "Modificar");

        codigoLabel_Eliminar.setText("Código");

        posicionLabel_Eliminar.setText("Posición");

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminarPanelLayout = new javax.swing.GroupLayout(eliminarPanel);
        eliminarPanel.setLayout(eliminarPanelLayout);
        eliminarPanelLayout.setHorizontalGroup(
            eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarPanelLayout.createSequentialGroup()
                        .addComponent(eliminarButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(eliminarPanelLayout.createSequentialGroup()
                        .addGroup(eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoLabel_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posicionLabel_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(posicionTextField_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(codigoTextField_Eliminar))
                        .addGap(40, 40, 40))))
        );
        eliminarPanelLayout.setVerticalGroup(
            eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel_Eliminar)
                    .addComponent(codigoTextField_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicionLabel_Eliminar)
                    .addComponent(posicionTextField_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(eliminarButton)
                .addGap(170, 170, 170))
        );

        contenidoPanel.add(eliminarPanel, "Eliminar");
        eliminarPanel.getAccessibleContext().setAccessibleName("");

        buscarPanel.setMaximumSize(new java.awt.Dimension(32767, 320));

        codigoLabel_Buscar.setText("Código");

        nombreLabel_Buscar.setText("Nombre");

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buscarPanelLayout = new javax.swing.GroupLayout(buscarPanel);
        buscarPanel.setLayout(buscarPanelLayout);
        buscarPanelLayout.setHorizontalGroup(
            buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscarPanelLayout.createSequentialGroup()
                        .addComponent(nombreLabel_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombreTextField_Buscar))
                    .addComponent(buscarButton)
                    .addGroup(buscarPanelLayout.createSequentialGroup()
                        .addComponent(codigoLabel_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(codigoTextField_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        buscarPanelLayout.setVerticalGroup(
            buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel_Buscar)
                    .addComponent(codigoTextField_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel_Buscar)
                    .addComponent(nombreTextField_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(buscarButton)
                .addGap(170, 170, 170))
        );

        contenidoPanel.add(buscarPanel, "Buscar");

        getContentPane().add(contenidoPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarRadioButtonActionPerformed
        ((CardLayout)contenidoPanel.getLayout()).show(contenidoPanel,"Modificar");
        
        
    }//GEN-LAST:event_modificarRadioButtonActionPerformed

    private void agregarRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarRadioButtonActionPerformed
        ((CardLayout)contenidoPanel.getLayout()).show(contenidoPanel,"Agregar");
        
        
    }//GEN-LAST:event_agregarRadioButtonActionPerformed

    private void buscarRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarRadioButtonActionPerformed
  
        ((CardLayout)contenidoPanel.getLayout()).show(contenidoPanel,"Buscar");
        
        
    }//GEN-LAST:event_buscarRadioButtonActionPerformed

    private void eliminarRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRadioButtonActionPerformed
 
        ((CardLayout)contenidoPanel.getLayout()).show(contenidoPanel,"Eliminar");
        
        
    }//GEN-LAST:event_eliminarRadioButtonActionPerformed

    private void liberarListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberarListaButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Liberar lista: "+alumnos.liberarLista());
    }//GEN-LAST:event_liberarListaButtonActionPerformed

    private void agregarInicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarInicioButtonActionPerformed
        String codigo=codigoTextField_Agregar.getText();
        String nombre=nombreTextField_Agregar.getText();
        
        boolean estado=alumnos.agregarInicio(codigo, nombre);
        
        JOptionPane.showMessageDialog(this, "Agregar inicio: "+estado);
    }//GEN-LAST:event_agregarInicioButtonActionPerformed

    private void agregarFinalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFinalButtonActionPerformed
        String codigo=codigoTextField_Agregar.getText();
        String nombre=nombreTextField_Agregar.getText();
        
        boolean estado=alumnos.agregarFinal(codigo, nombre);
        
        JOptionPane.showMessageDialog(this, "Agregar final: "+estado);
    }//GEN-LAST:event_agregarFinalButtonActionPerformed

    private void insertarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarButtonActionPerformed
        String codigo=codigoTextField_Agregar.getText();
        String nombre=nombreTextField_Agregar.getText();
        int posicion=Integer.parseInt(posicionTextField_Agregar.getText());
        
        boolean estado=alumnos.insertarNodo(codigo, nombre,posicion);
        
        JOptionPane.showMessageDialog(this, "Insertar alumno: "+estado);
    }//GEN-LAST:event_insertarButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        String codigo=codigoTextField_Modificar.getText();
        String nuevoNombre=nuevoNombTextField_Modificar.getText();
        
        boolean estado= alumnos.modificarNombre(codigo, nuevoNombre);
        
        JOptionPane.showMessageDialog(this, "Modificar nombre: "+estado);
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        boolean estado;
        
        if(!codigoTextField_Eliminar.getText().isBlank()){
            String codigo=codigoTextField_Eliminar.getText();
            estado=alumnos.eliminarNodoCod(codigo);
        }
        else{
            int posicion=Integer.parseInt(posicionTextField_Eliminar.getText());
            estado=alumnos.eliminarNodoPos(posicion);
        }
        
        JOptionPane.showMessageDialog(this, "Eliminar alumno: "+estado);
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        String alumno="valor inicial";
        
        if(!codigoTextField_Buscar.getText().isBlank()){
            String codigo=codigoTextField_Buscar.getText();
            alumno=alumnos.buscarNodoCod(codigo);
        }
        else{
            String nombre=nombreTextField_Buscar.getText();
            alumno=alumnos.buscarNodoNomb(nombre);
        }
        
        JOptionPane.showMessageDialog(this, "Alumno: "+alumno);
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void mostrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarButtonActionPerformed
        String informacion=alumnos.mostrarCadena();
        
        JOptionPane.showMessageDialog(this, informacion);
    }//GEN-LAST:event_mostrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarFinalButton;
    private javax.swing.JButton agregarInicioButton;
    private javax.swing.JPanel agregarPanel;
    private javax.swing.JRadioButton agregarRadioButton;
    private javax.swing.JPanel botonesPanel;
    private javax.swing.JButton buscarButton;
    private javax.swing.JPanel buscarPanel;
    private javax.swing.JRadioButton buscarRadioButton;
    private javax.swing.JLabel codigoLabel_Agregar;
    private javax.swing.JLabel codigoLabel_Buscar;
    private javax.swing.JLabel codigoLabel_Eliminar;
    private javax.swing.JLabel codigoLabel_Modificar;
    private javax.swing.JTextField codigoTextField_Agregar;
    private javax.swing.JTextField codigoTextField_Buscar;
    private javax.swing.JTextField codigoTextField_Eliminar;
    private javax.swing.JTextField codigoTextField_Modificar;
    private javax.swing.JPanel contenidoPanel;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JPanel eliminarPanel;
    private javax.swing.JRadioButton eliminarRadioButton;
    private javax.swing.JButton insertarButton;
    private javax.swing.JButton liberarListaButton;
    private javax.swing.JButton modificarButton;
    private javax.swing.JPanel modificarPanel;
    private javax.swing.JRadioButton modificarRadioButton;
    private javax.swing.JButton mostrarButton;
    private javax.swing.JLabel nombreLabel_Agregar;
    private javax.swing.JLabel nombreLabel_Buscar;
    private javax.swing.JTextField nombreTextField_Agregar;
    private javax.swing.JTextField nombreTextField_Buscar;
    private javax.swing.JLabel nuevoNombLabel_Modificar;
    private javax.swing.JTextField nuevoNombTextField_Modificar;
    private javax.swing.ButtonGroup operacionesButtonGroup;
    private javax.swing.JLabel operacionesLabel;
    private javax.swing.JPanel paginasPanel;
    private javax.swing.JLabel posicionLabel_Agregar;
    private javax.swing.JLabel posicionLabel_Eliminar;
    private javax.swing.JTextField posicionTextField_Agregar;
    private javax.swing.JTextField posicionTextField_Eliminar;
    // End of variables declaration//GEN-END:variables
}
